### ISSUE TITLE
Navigation states do not terminate correctly

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/robot_smach_states#17]
Nav states are concurrent but that makes handling crtl-C weird.
We fixed this once, but don't know how anymore.

**Comment by rokusottervanger** [comment]
I believe this is fixed after the re-write of the navigation state, right?

**Comment by LoyVanBeek** [comment]
Can this be closed?

**Comment by rokusottervanger** [comment]
It still errors when ctrl-Cing during navigation, but it shuts down. So I guess this can be closed, right?

**Comment by LoyVanBeek** [comment]
I think so. We'll have to see if it ever pops up again.
