### ISSUE TITLE
Reset ED when starting a challenge

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/robot_smach_states#26]
When testing manipulation challenge, it seemed that ED was not reset upon the start of the challenge. This will lead to many problems in competition!!! I don't know if this is the case for other challenges

**Comment by LoyVanBeek** [comment]
Fixed in https://github.com/tue-robotics/robot_smach_states/commit/585e52ddf50c0830fbfbed0a30cc15bfa9a0e205#diff-2e276f7c146e0524dc460b1009f7e9b3R29
