### ISSUE TITLE
Clear world model navigation state

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/robot_smach_states#36]
Clear the world model or at least the blocking objects and do not immediately say that the goal is unreachable

**Comment by LoyVanBeek** [comment]
Clearing the worldmodel is a bit rigourous: you also forget the thing you are navigating towards.

**Comment by reinzor** [comment]
Of course some more intelligent solution such as unknown objects on the
ground or something. But this has already been discussed multiple times.

**Comment by LoyVanBeek** [comment]
Can this be closed?

**Comment by reinzor** [comment]
​Yes​

-Rein
