### ISSUE TITLE
VariableDesignators: Make clear which states sets the variable and which only read them

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/robot_smach_states#40]

**Comment by rokusottervanger** [comment]
Do you mean by naming conventions?

**Comment by LoyVanBeek** [comment]
Nope, was working on making variable designators unwritable unless explicitly marked as writeable.

**Comment by rokusottervanger** [comment]
What exactly would you do with an unwritable variable designator?

2015-08-26 13:10 GMT+02:00 Loy <notifications@github.com>:

**Comment by LoyVanBeek** [comment]
Just get data from it, as you would with any designator. But to write to it, the writing state has to have the variable explicitly as writeable. 
In your code, you can see exactly which states then write to any VariableDesignator and which just read. 
Suggestions welcome.

**Comment by rokusottervanger** [comment]
So when one state needs to write to a designator, and a second one needs to read that information, the designator should be writable, right? If that's the case, could you give an example of a situation where a designator should not be writable?

**Comment by LoyVanBeek** [comment]
Well, the reader does not need to know that a designator is a VariableDesignator or whatever. Only the writer must know that it can write, and should check that it is writeable. 
Readers should only check the resolve_type.
