### ISSUE TITLE
Update InitializeWorldModel state

### ISSUE THREAD

**Issue by LFBFerreira** [tue-robotics/robot_smach_states#44]
Something changed in the setup or the world Model, and the state InitializeWorldModel was crashing. I commented the lines, but Sjoerd should check which are needed.

Check robot_smach_states->world_model.py

**Comment by Rayman** [comment]
@LFBFerreira is this fixed?

**Comment by LFBFerreira** [comment]
Think so, At least @svddries was on it two weeks ago and last time i checked the test executive was working
