### ISSUE TITLE
scanForHuman state in human_interaction crashes

### ISSUE THREAD

**Issue by LFBFerreira** [tue-robotics/robot_smach_states#46]
When running this command:

    entities_found = robot.ed.segment_kinect(max_sensor_range=3)

i get the following error:

    AttributeError: ED instance has no attribute 'segment_kinect'

What changed here Sjoerd? For now i will leave this commented and he will never find the object he is looking for (people in this case)

**Comment by reinzor** [comment]
Is this issue solved?

**Comment by LoyVanBeek** [comment]
No, even worse, things changed even more. @svddries knows best ATM. 
The current challenge_person_recognition uses the new robot.ed.detect_persons.
