### ISSUE TITLE
Place and grasp poses seem to be wrong

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/robot_smach_states#52]
Using robot_smach_states.Grab()

![grasp_point_to_high](https://cloud.githubusercontent.com/assets/4176023/13252674/5ea3be4a-da38-11e5-97a3-92bf1f073f1f.png)
![too_high_2](https://cloud.githubusercontent.com/assets/4176023/13252675/5ea4a72e-da38-11e5-8b64-9b492a472c56.png)
![wrong_pose](https://cloud.githubusercontent.com/assets/4176023/13252676/5ea57dc0-da38-11e5-9603-07f7e99623d4.png)

**Comment by LoyVanBeek** [comment]
We need to clean up the various grab-states we have an use/optimize ONE

**Comment by reinzor** [comment]
Issues solved:

- [ ] Entity gets updated before grasp

Some issues still left:

- [ ] Grasp pose still seems to be wrong if I check visualization
- [ ] Get rid of SjoerdsGrab

**Comment by Rayman** [comment]
Did we get rid of SjoerdsGrab?
